service: serverless-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: GET
          path: '/'
  workaround:
    handler: dist/workaround.handler
    events:
      - http:
          method: POST
          path: '/users'
      - http:
          method: POST
          path: '/users/email-verify'
      - http:
          method: POST
          path: '/users/login'
      - http:
          method: GET
          path: '/users/{id}'

custom:
  serverless-offline:
    noPrependStageInUrl: true

package:
  patterns:
    - '!**'
    - package.json
    - package-lock.json
    - dist/**
    - config/production.js